In [3]:
import numpy as np

## Datatypes and Attributes

In [4]:
# 1-dimensonal array -> vector
a1=np.array([1,2,3])
a1.shape,a1.ndim,a1.dtype,a1.size

((3,), 1, dtype('int64'), 3)

In [5]:
# 2 dimensonal array ->matrix
a2=np.array([[1,2,3],[4,5,6]])
a2.shape,a2.ndim,a2.dtype,a1.size

((2, 3), 2, dtype('int64'), 3)

In [6]:
#shape -> (rows,columns)
#ndim -> dimensons of array (1d,2d)
#size -> no of elements in array 

## Creating Numpy arrays

In [7]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.random.randint(10,size=(2,3))

array([[5, 3, 4],
       [7, 1, 4]], dtype=int32)

In [20]:
#make the random numbers same
np.random.seed(7)
np.random.randint(10,size=(2,3))

array([[4, 9, 6],
       [3, 3, 7]], dtype=int32)

## Viewing Arrays 

In [24]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[0, 1, 0, 6, 2],
         [0, 2, 4, 4, 1],
         [0, 0, 2, 3, 7],
         [6, 9, 3, 5, 6]],

        [[8, 6, 7, 3, 8],
         [5, 6, 4, 2, 7],
         [9, 6, 8, 6, 1],
         [0, 7, 6, 8, 5]],

        [[4, 3, 0, 7, 4],
         [0, 8, 5, 0, 7],
         [5, 1, 5, 9, 4],
         [1, 9, 6, 5, 6]]],


       [[[8, 5, 9, 4, 6],
         [0, 6, 2, 3, 1],
         [6, 7, 0, 0, 4],
         [7, 0, 2, 9, 6]],

        [[1, 2, 2, 8, 9],
         [7, 2, 4, 7, 7],
         [9, 1, 0, 1, 8],
         [7, 4, 6, 1, 4]],

        [[8, 7, 3, 3, 6],
         [4, 9, 5, 7, 9],
         [9, 7, 6, 9, 8],
         [8, 6, 2, 2, 2]]]], dtype=int32)

In [26]:
a4[ : , : , : , :4]

array([[[[0, 1, 0, 6],
         [0, 2, 4, 4],
         [0, 0, 2, 3],
         [6, 9, 3, 5]],

        [[8, 6, 7, 3],
         [5, 6, 4, 2],
         [9, 6, 8, 6],
         [0, 7, 6, 8]],

        [[4, 3, 0, 7],
         [0, 8, 5, 0],
         [5, 1, 5, 9],
         [1, 9, 6, 5]]],


       [[[8, 5, 9, 4],
         [0, 6, 2, 3],
         [6, 7, 0, 0],
         [7, 0, 2, 9]],

        [[1, 2, 2, 8],
         [7, 2, 4, 7],
         [9, 1, 0, 1],
         [7, 4, 6, 1]],

        [[8, 7, 3, 3],
         [4, 9, 5, 7],
         [9, 7, 6, 9],
         [8, 6, 2, 2]]]], dtype=int32)

## Arthmetic Operations

In [31]:
ones=np.ones((1,3))
a=[6,6,6]

In [32]:
ones+a

array([[7., 7., 7.]])

In [33]:
ones-a

array([[-5., -5., -5.]])

In [34]:
a*ones

array([[6., 6., 6.]])

In [35]:
a/ones

array([[6., 6., 6.]])

In [36]:
a//ones

array([[6., 6., 6.]])

In [37]:
a%ones

array([[0., 0., 0.]])

In [38]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [39]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [40]:
np.min(a)

np.int64(6)

In [41]:
np.max(a)

np.int64(6)

In [42]:
np.mean(a)

np.float64(6.0)

In [43]:
np.std(a)

np.float64(0.0)

In [45]:
# variances -> higher variance is wider range of  numbers
#-> lower variances is lower range of numbers
high_var=np.array([1,200,4000,50000])
np.var(high_var)

np.float64(445400725.1875)

In [47]:
low_var=np.array([1,3,5,7,9])
np.var(low_var)

np.float64(8.0)

In [48]:
#std -> how far are they from mean
np.std(low_var)

np.float64(2.8284271247461903)

## Reshape and Transpose   

In [59]:
a2.shape

(2, 3)

In [61]:
a2_reshape = a2.reshape((2,3,1))
a2_reshape



array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [62]:
a2.T  # Transpose - switches the axis

array([[1, 4],
       [2, 5],
       [3, 6]])

In [64]:
a2.T.shape # ->before its (2,3)

(3, 2)

## DOT PRODUCT 

In [69]:

mat1=np.random.randint(10,size=(5,3))
mat2=np.random.randint(10,size=(5,3))


In [71]:
mat1

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]], dtype=int32)

In [72]:
mat2


array([[2, 3, 8],
       [1, 3, 3],
       [3, 7, 0],
       [1, 9, 9],
       [0, 4, 7]], dtype=int32)

In [73]:
#elementary multiplications
mat1*mat2

array([[12, 21, 56],
       [ 8,  3, 15],
       [27, 56,  0],
       [ 4, 27,  0],
       [ 0, 20,  0]], dtype=int32)

In [77]:
# -> Dot product (n,m)(r,p) then if n==p or m==r then we can do dot product
mat3=np.dot(mat1,mat2.T)
mat3

array([[ 89,  48,  67, 132,  77],
       [ 59,  26,  31,  62,  39],
       [114,  60,  83, 162,  95],
       [ 17,  13,  33,  31,  12],
       [ 21,  18,  44,  48,  20]], dtype=int32)

## Comparison Operators

In [80]:
arr=np.array([2,3,7])
arr1=np.array([2,4,1])
arr>arr1

array([False, False,  True])

In [81]:
arr > 5

array([False, False,  True])

In [82]:
arr==arr1

array([ True, False, False])

In [83]:
arr==arr

array([ True,  True,  True])

In [84]:
arr==7

array([False, False,  True])

## Sorting Arrays


In [86]:
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[8, 1, 1, 7, 9],
       [9, 3, 6, 7, 2],
       [0, 3, 5, 9, 4]], dtype=int32)

In [88]:
np.sort(random_array)#-> sorts each col

array([[1, 1, 7, 8, 9],
       [2, 3, 6, 7, 9],
       [0, 3, 4, 5, 9]], dtype=int32)

In [90]:
np.argsort(random_array) #-> sorts and shows indx

array([[1, 2, 3, 0, 4],
       [4, 1, 2, 3, 0],
       [0, 1, 4, 2, 3]])

In [94]:
np.argmax(random_array,axis=0) #-> checks row wise

array([1, 1, 1, 2, 0])

In [96]:
np.argmax(random_array,axis=1) # -> checks col wise

array([4, 0, 3])